# Generated by Django 2.0.1 on 2018-02-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='name',
            new_name='name_dog',
        ),
    ]
